import {
  Button,
  Dialog,
  DialogActions,
  DialogBody,
  DialogContent,
  DialogSurface,
  DialogTitle,
  Input,
  Spinner,
  Text,
  makeStyles,
  shorthands,
  tokens,
} from '@fluentui/react-components';
import { Call, Device } from '@twilio/voice-sdk';
import { SyncClient, SyncMap } from 'twilio-sync';

import { CIFV2 } from '../cif/CIFV2';
import { GlobalStore } from '../common/GlobalStore/GlobalStore';
import { GlobalStoreParameters } from '../common/GlobalStore/GlobalStoreParameters';
import { HIAConversationEventHelper } from '../common/utility/HIAConversationEventHelper';
import { INotificationTemplate } from '../interfaces/INotificationTemplate';
import React from 'react';
import { Utils } from '../common/utility/Utils';

// Voice token endpoint mints a JWT carrying VoiceGrant + SyncGrant.
// Kept separate from /token (chat) because merging grants poisons the
// Conversations SDK's internal Sync subscription.
const VOICE_TOKEN_URL = 'https://chattryoutautogeneratedauthservice-6300.twil.io/voice-token';
const USERS_URL = 'https://chattryoutautogeneratedauthservice-6300.twil.io/users';
const DEFAULT_AGENT_IDENTITY = 'Admin';
const VOICE_INTENT_FAMILY_ID = '14f7c663-ed81-46d4-8cec-4cb1432bce57';
const SESSION_TEMPLATE = 'msdyn_3p_session'; // shared with chat for now

interface AgentUser {
  identity: string;
  friendlyName: string;
}

type CallStatus = 'idle' | 'incoming' | 'in-progress' | 'ended';
type DeviceStatus = 'connecting' | 'ready' | 'unavailable';

interface ActiveCallLike {
  callSid: string;
  from: string;
  isSimulated: boolean;
  call?: Call; // present only for real calls
}

const useStyles = makeStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    ...shorthands.padding('20px'),
    ...shorthands.gap('12px'),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  header: { fontSize: '18px', fontWeight: 'bold' },
  statusRow: { display: 'flex', alignItems: 'center', ...shorthands.gap('8px') },
  callCard: {
    ...shorthands.padding('16px'),
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
    ...shorthands.borderRadius('8px'),
    backgroundColor: tokens.colorNeutralBackground2,
  },
  controls: { display: 'flex', ...shorthands.gap('8px'), marginTop: '12px' },
  errorText: { color: tokens.colorPaletteRedForeground1 },
  devNote: {
    ...shorthands.padding('8px', '12px'),
    backgroundColor: tokens.colorNeutralBackground3,
    ...shorthands.borderRadius('4px'),
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
});

const TwilioVoicePanel: React.FC = () => {
  const styles = useStyles();
  const [agentIdentity, setAgentIdentity] = React.useState<string>(DEFAULT_AGENT_IDENTITY);
  const [agentFriendlyName, setAgentFriendlyName] = React.useState<string>('');
  const [availableAgents, setAvailableAgents] = React.useState<AgentUser[]>([]);
  const [showSwitchDialog, setShowSwitchDialog] = React.useState<boolean>(false);
  const [switchAgentInput, setSwitchAgentInput] = React.useState<string>('');
  const [deviceStatus, setDeviceStatus] = React.useState<DeviceStatus>('connecting');
  const [activeCall, setActiveCall] = React.useState<ActiveCallLike | null>(null);
  const [callStatus, setCallStatus] = React.useState<CallStatus>('idle');
  const [error, setError] = React.useState<string | null>(null);
  const [isMuted, setIsMuted] = React.useState<boolean>(false);
  const [debugCallSid, setDebugCallSid] = React.useState<string>('');
  const [debugResult, setDebugResult] = React.useState<string>('');

  // Load the agent list once on mount so the switch dropdown is populated.
  React.useEffect(() => {
    (async () => {
      try {
        const resp = await fetch(USERS_URL);
        if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
        const data = await resp.json();
        const agents: AgentUser[] = (data.users || []).filter(
          (u: AgentUser) => !u.identity.startsWith('customer_'),
        );
        setAvailableAgents(agents);
        const me = agents.find((a) => a.identity === agentIdentity);
        if (me?.friendlyName) setAgentFriendlyName(me.friendlyName);
      } catch (err) {
        console.warn('[Voice] could not load agents:', err);
      }
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleOpenSwitch = () => {
    setSwitchAgentInput(agentIdentity);
    setShowSwitchDialog(true);
  };

  // Switching identity tears down everything: active call, Device, Sync client.
  // Setting agentIdentity re-runs the device-init effect which recreates them
  // for the new identity. Mirrors the chat panel's disconnect-then-reinit flow.
  const handleSwitchAgent = () => {
    const next = switchAgentInput.trim();
    if (!next || next === agentIdentity) {
      setShowSwitchDialog(false);
      return;
    }
    if (activeCall) {
      try { activeCall.call?.disconnect(); } catch { /* ignore */ }
    }
    const friendly = availableAgents.find((a) => a.identity === next)?.friendlyName || '';
    setAgentFriendlyName(friendly);
    setAgentIdentity(next);
    setShowSwitchDialog(false);
    setActiveCall(null);
    setCallStatus('idle');
    setDeviceStatus('connecting');
    setError(null);
  };

  // Mirrors the chat panel's session<->conversation maps but keyed by CallSid.
  const sessionToCallMap = React.useRef<Map<string, string>>(new Map());
  const callToSessionMap = React.useRef<Map<string, string>>(new Map());
  const loadedCallsRef = React.useRef<Set<string>>(new Set());
  // The Sync client is created when the device token is fetched (same JWT carries
  // VoiceGrant + SyncGrant). Live for the panel's lifetime; per-call SyncMap
  // subscriptions are layered on top.
  const syncClientRef = React.useRef<SyncClient | null>(null);

  // Twilio creates two CallSids per call: a parent (inbound PSTN leg) and a
  // child (Client dial leg). <Start><Transcription> attaches to the parent,
  // so transcripts land in `call-transcripts-${parentCallSid}`. The Voice SDK
  // on the agent side sees the child CallSid in `call.parameters.CallSid`.
  // The parent is passed via TwiML <Parameter name="parentCallSid"/>.
  // We use the parent for Sync subscription AND for the HIA conversationId
  // so they're consistent with what the connector reads.
  const getRealCallSid = (call: Call): string => {
    const fromCustomParam = call.customParameters?.get('parentCallSid');
    if (fromCustomParam) return fromCustomParam;
    return call.parameters.CallSid || `pending_${Date.now()}`;
  };

  // Subscribe to the Sync map the voice-transcript-webhook Function writes
  // each final transcript into. Customer items raise onCustomerMessageReceived;
  // agent items are written too (for full-context LLM input via the connector)
  // but do not raise CIF events.
  const subscribeToTranscripts = React.useCallback(
    (callSid: string): (() => void) => {
      const client = syncClientRef.current;
      if (!client) {
        console.warn('[Sync] no client available; transcripts will not stream');
        return () => {};
      }

      let map: SyncMap | null = null;
      let cancelled = false;

      (async () => {
        try {
          // open_or_create — the Function may not have created the map yet if
          // the customer hasn't spoken; opening here gives us a live handle.
          map = await client.map({
            id: `call-transcripts-${callSid}`,
            mode: 'open_or_create',
          });
          if (cancelled) {
            map.close();
            return;
          }

          map.on('itemAdded', async ({ item }: { item: { data: any; key: string } }) => {
            const { speaker, messageId, text, timestamp } = item.data || {};
            console.log('[Sync] transcript item', { speaker, messageId, text });
            if (speaker !== 'customer') return;
            await HIAConversationEventHelper.raiseCustomerMessageReceived(
              callSid,
              messageId || item.key,
              timestamp,
            );
          });
        } catch (err) {
          console.error('[Sync] failed to open transcript map for', callSid, err);
        }
      })();

      return () => {
        cancelled = true;
        try { map?.removeAllListeners(); map?.close(); } catch { /* ignore */ }
      };
    },
    [],
  );

  // ============================================================
  // Shared CIF handoff: notify -> Accept -> createSession -> raise load.
  // Used by both the real `device.on('incoming')` path and the simulate button
  // so they exercise identical CIF behavior.
  // ============================================================
  const runCifHandoff = React.useCallback(
    async (
      callSid: string,
      fromLabel: string,
      // Invoked the instant the agent accepts the CIF toast, BEFORE the slower
      // createSession + raiseConversationLoad work runs. Real-call path passes
      // call.accept here so audio bridges before Twilio's <Dial timeout> fires;
      // simulated calls leave it undefined.
      onAcceptedBeforeSession?: () => void,
    ): Promise<boolean> => {
      if (!Utils.isCIFAvailable()) {
        console.warn('[CIF] not available — auto-accepting without notify');
        onAcceptedBeforeSession?.();
        return true;
      }

      const notificationTemplate = GlobalStore.getInstance().get(
        GlobalStoreParameters.NOTIFICATION_TEMPLATE,
      ) as INotificationTemplate;

      const cancellationToken = Utils.generateUUID();
      const correlationId = Utils.generateUUID();

      console.log(`[CIF] voice notify for ${fromLabel} (${correlationId})`);
      const resultJSON = await CIFV2.getInstance().notifyEvent(
        notificationTemplate.uniqueName,
        cancellationToken,
        correlationId,
      );
      const result = JSON.parse(resultJSON);
      if (result.actionName !== 'Accept') {
        console.log('[CIF] voice notify rejected/timeout');
        return false;
      }

      // Bridge audio NOW. createSession + raiseConversationLoad are slow and
      // would push us past Twilio's <Dial timeout> if we waited.
      onAcceptedBeforeSession?.();

      const sessionId = await CIFV2.getInstance().createSession(
        SESSION_TEMPLATE,
        correlationId,
        {},
      );
      sessionToCallMap.current.set(sessionId, callSid);
      callToSessionMap.current.set(callSid, sessionId);

      if (!loadedCallsRef.current.has(callSid)) {
        await HIAConversationEventHelper.raiseConversationLoad(
          callSid,
          VOICE_INTENT_FAMILY_ID,
        );
        loadedCallsRef.current.add(callSid);
        console.log('[HIA] onConversationLoad raised for call', callSid);
      }
      return true;
    },
    [],
  );

  // ============================================================
  // Real inbound call handler (Device 'incoming' event).
  // ============================================================
  const handleIncomingCall = React.useCallback(
    async (call: Call) => {
      const from = call.parameters.From || 'Unknown';
      const callSid = getRealCallSid(call);
      setActiveCall({ callSid, from, isSimulated: false, call });
      setCallStatus('incoming');

      let unsubscribeTranscripts: (() => void) | null = null;

      // Wire call lifecycle listeners up front so they fire even if Twilio
      // cancels the leg between notify-Accept and our session work.
      call.on('accept', () => {
        setCallStatus('in-progress');
        unsubscribeTranscripts = subscribeToTranscripts(callSid);
      });
      call.on('disconnect', () => {
        setCallStatus('ended');
        setActiveCall(null);
        setIsMuted(false);
        unsubscribeTranscripts?.();
      });
      call.on('cancel', () => {
        setCallStatus('idle');
        setActiveCall(null);
        unsubscribeTranscripts?.();
      });
      call.on('error', (e: Error) => {
        console.error('[Voice] call error', e);
        setError(e.message);
      });

      // call.accept() is invoked by runCifHandoff the instant the agent clicks
      // Accept on the CIF toast — before the slower createSession +
      // raiseConversationLoad steps. This keeps Twilio's <Dial timeout> happy.
      const accepted = await runCifHandoff(callSid, from, () => {
        try { call.accept(); } catch (e) { console.error('[Voice] accept failed', e); }
      }).catch((err) => {
        console.error('[CIF] error in voice handoff', err);
        return false;
      });

      if (!accepted) {
        try { call.reject(); } catch { /* ignore */ }
        setActiveCall(null);
        setCallStatus('idle');
        return;
      }
      call.on('disconnect', () => {
        setCallStatus('ended');
        setActiveCall(null);
        setIsMuted(false);
        unsubscribeTranscripts?.();
      });
      call.on('cancel', () => {
        setCallStatus('idle');
        setActiveCall(null);
        unsubscribeTranscripts?.();
      });
      call.on('error', (e: Error) => {
        console.error('[Voice] call error', e);
        setError(e.message);
      });
    },
    [runCifHandoff, subscribeToTranscripts],
  );

  // ============================================================
  // Simulated incoming call (no audio, no SDK) — exercises the same CIF flow.
  // Useful before the voice token endpoint exists.
  // ============================================================
  const handleSimulateIncomingCall = React.useCallback(async () => {
    if (callStatus !== 'idle' && callStatus !== 'ended') return;

    // If a CallSid is in the debug input, use it for the simulated call so
    // HIA receives a real CallSid that has transcripts in Sync. End-to-end
    // test: full CIF flow + real connector data + real intent suggestion.
    // Otherwise generate a SIM_ id (CIF flow exercised, but connector returns empty).
    const userProvidedSid = debugCallSid.trim();
    const callSid = userProvidedSid || `SIM_${Utils.generateUUID()}`;
    const from = userProvidedSid
      ? `${userProvidedSid.slice(0, 14)}… (e2e test)`
      : '+1-555-0100 (simulated)';
    setActiveCall({ callSid, from, isSimulated: true });
    setCallStatus('incoming');

    const accepted = await runCifHandoff(callSid, from).catch((err) => {
      console.error('[CIF] error in simulated voice handoff', err);
      return false;
    });

    if (!accepted) {
      setActiveCall(null);
      setCallStatus('idle');
      return;
    }
    setCallStatus('in-progress');
  }, [callStatus, runCifHandoff, debugCallSid]);

  // ============================================================
  // Device lifecycle. Failure here is non-fatal — the simulate button still works.
  // ============================================================
  React.useEffect(() => {
    let cancelled = false;
    let createdDevice: Device | null = null;

    const init = async () => {
      try {
        const resp = await fetch(
          `${VOICE_TOKEN_URL}?identity=${encodeURIComponent(agentIdentity)}`,
        );
        if (!resp.ok) throw new Error(`token fetch ${resp.status}`);
        const { token } = await resp.json();
        if (cancelled) return;

        createdDevice = new Device(token, { logLevel: 1 });
        createdDevice.on('incoming', handleIncomingCall);
        createdDevice.on('error', (e: Error) => {
          console.error('[Voice] device error', e);
          setError(e.message);
        });
        createdDevice.on('tokenWillExpire', async () => {
          const r = await fetch(
            `${VOICE_TOKEN_URL}?identity=${encodeURIComponent(agentIdentity)}`,
          );
          const { token: fresh } = await r.json();
          createdDevice?.updateToken(fresh);
          // Same JWT carries the SyncGrant; refresh the Sync client too.
          try { syncClientRef.current?.updateToken(fresh); } catch (e) { console.warn('[Sync] token refresh failed', e); }
        });

        // Same token (VoiceGrant + SyncGrant) drives both clients.
        try {
          syncClientRef.current = new SyncClient(token);
          console.log('[Sync] client initialized');
        } catch (e) {
          console.warn('[Sync] client init failed (transcripts will not stream)', e);
        }

        await createdDevice.register();
        if (cancelled) {
          createdDevice.destroy();
          return;
        }
        setDeviceStatus('ready');
        console.log('[Voice] device registered as', agentIdentity);
      } catch (err) {
        if (cancelled) return;
        console.warn('[Voice] device unavailable (no token endpoint?):', err);
        setDeviceStatus('unavailable');
      }
    };

    init();
    return () => {
      cancelled = true;
      createdDevice?.removeAllListeners();
      createdDevice?.destroy();
      try { syncClientRef.current?.shutdown(); } catch { /* ignore */ }
      syncClientRef.current = null;
    };
  }, [agentIdentity, handleIncomingCall]);

  // ============================================================
  // CIF session-switch / close handlers — only the close handler matters for
  // voice (no rehydrate-from-call needed). Using a ref to avoid double-registering
  // on re-renders.
  // ============================================================
  const cifHandlersRegistered = React.useRef(false);
  React.useEffect(() => {
    if (cifHandlersRegistered.current || !Utils.isCIFAvailable()) return;
    cifHandlersRegistered.current = true;

    CIFV2.getInstance().addHandler('onSessionClosed', async (eventData: string) => {
      const { sessionId } = JSON.parse(eventData);
      const callSid = sessionToCallMap.current.get(sessionId);
      if (callSid) {
        sessionToCallMap.current.delete(sessionId);
        callToSessionMap.current.delete(callSid);
        loadedCallsRef.current.delete(callSid);
        console.log('[CIF] cleaned up voice session', sessionId, 'call', callSid);
      }
    });
  }, []);

  // Dev tool: fires HIA's IntentAssistRefresh event for the given CallSid.
  // This is the on-demand refresh CIF event the HIA client driver listens for
  // (separate from onConversationLoad/onCustomerMessageReceived) — single endpoint
  // hit, carries intentFamilyId, triggers connector + intent re-evaluation.
  const handleTriggerHIATest = React.useCallback(async () => {
    const callSid = debugCallSid.trim();
    if (!callSid) {
      setDebugResult('Enter a CallSid first');
      return;
    }
    setDebugResult('Firing IntentAssistRefresh…');
    try {
      await CIFV2.getInstance().raiseEvent(
        'IntentAssistRefresh',
        JSON.stringify({
          conversationId: callSid,
          intentFamilyId: VOICE_INTENT_FAMILY_ID,
        }),
      );
      setDebugResult(`✅ Raised IntentAssistRefresh for ${callSid} (intentFamily=${VOICE_INTENT_FAMILY_ID}).`);
    } catch (err) {
      setDebugResult(`❌ Error: ${err instanceof Error ? err.message : String(err)}`);
    }
  }, [debugCallSid]);

  const handleHangUp = () => {
    if (!activeCall) return;
    if (activeCall.isSimulated) {
      setCallStatus('ended');
      setActiveCall(null);
      setIsMuted(false);
    } else {
      activeCall.call?.disconnect();
    }
  };

  const handleToggleMute = () => {
    if (!activeCall || activeCall.isSimulated) {
      setIsMuted((m) => !m);
      return;
    }
    const next = !isMuted;
    activeCall.call?.mute(next);
    setIsMuted(next);
  };

  const switchDialog = (
    <Dialog open={showSwitchDialog} onOpenChange={(_, d) => setShowSwitchDialog(d.open)}>
      <DialogSurface>
        <DialogBody>
          <DialogTitle>Switch Agent</DialogTitle>
          <DialogContent>
            <Text size={300} style={{ display: 'block', marginBottom: '12px' }}>
              Currently logged in as: <strong>{agentFriendlyName || agentIdentity}</strong>
            </Text>
            {availableAgents.length > 0 ? (
              <select
                value={switchAgentInput}
                onChange={(e) => setSwitchAgentInput(e.target.value)}
                style={{
                  width: '100%',
                  padding: '8px 10px',
                  fontSize: '14px',
                  border: `1px solid ${tokens.colorNeutralStroke1}`,
                  borderRadius: '4px',
                  outline: 'none',
                  backgroundColor: tokens.colorNeutralBackground1,
                  color: tokens.colorNeutralForeground1,
                  cursor: 'pointer',
                }}
              >
                {availableAgents.map((a) => (
                  <option key={a.identity} value={a.identity}>
                    {a.friendlyName ? `${a.friendlyName} (${a.identity})` : a.identity}
                  </option>
                ))}
              </select>
            ) : (
              <Input
                value={switchAgentInput}
                onChange={(_, d) => setSwitchAgentInput(d.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSwitchAgent()}
                placeholder="Enter new agent identity"
                style={{ width: '100%' }}
                autoFocus
              />
            )}
          </DialogContent>
          <DialogActions>
            <Button appearance="subtle" onClick={() => setShowSwitchDialog(false)}>Cancel</Button>
            <Button appearance="primary" onClick={handleSwitchAgent} disabled={!switchAgentInput.trim()}>
              Switch
            </Button>
          </DialogActions>
        </DialogBody>
      </DialogSurface>
    </Dialog>
  );

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        📞 Voice —{' '}
        <span
          onClick={handleOpenSwitch}
          title="Click to switch agent"
          style={{ cursor: 'pointer', color: tokens.colorBrandForeground1, textDecoration: 'underline' }}
        >
          {agentFriendlyName || agentIdentity}
        </span>
      </div>

      <div className={styles.statusRow}>
        {deviceStatus === 'connecting' && (
          <>
            <Spinner size="tiny" />
            <Text size={200}>Registering voice device…</Text>
          </>
        )}
        {deviceStatus === 'ready' && (
          <Text size={200} style={{ color: tokens.colorPaletteGreenForeground1 }}>
            ● Device ready (real calls will ring this client)
          </Text>
        )}
        {deviceStatus === 'unavailable' && (
          <Text size={200} style={{ color: tokens.colorNeutralForeground3 }}>
            ○ Real device unavailable — use Simulate button below
          </Text>
        )}
      </div>

      {error && <Text className={styles.errorText}>Voice error: {error}</Text>}

      {(callStatus === 'idle' || callStatus === 'ended') && (
        <>
          <Text>{callStatus === 'ended' ? 'Call ended.' : 'Waiting for incoming calls…'}</Text>
          <div>
            <Button appearance="primary" onClick={handleSimulateIncomingCall}>
              {callStatus === 'ended' ? '📞 Simulate Another Call' : '📞 Simulate Incoming Call'}
            </Button>
          </div>
          <div className={styles.devNote}>
            Simulate triggers the same CIF flow a real call would: notify toast →
            on Accept, creates a <strong>{SESSION_TEMPLATE}</strong> session and
            raises <strong>onConversationLoad</strong>.
            If a CallSid is set below, simulate uses it so HIA gets real Sync data;
            otherwise it generates a SIM_ id (empty connector data).
          </div>

          <div style={{ marginTop: '16px', padding: '12px', backgroundColor: tokens.colorNeutralBackground3, borderRadius: '4px' }}>
            <Text size={300} weight="semibold" style={{ display: 'block', marginBottom: '8px' }}>
              🧪 Debug: Test with a real CallSid
            </Text>
            <Text size={200} style={{ display: 'block', marginBottom: '8px', color: tokens.colorNeutralForeground3 }}>
              <strong>Trigger HIA</strong>: fires <code>IntentAssistRefresh</code> CIF event
              (HIA's on-demand refresh) — single HIA endpoint hit, validates connector + Dataverse mapping.
              <br/>
              <strong>Simulate</strong> (button above): same CIF flow as a real call, also using this CallSid
              if set — full end-to-end test.
            </Text>
            <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
              <Input
                value={debugCallSid}
                onChange={(_, d) => setDebugCallSid(d.value)}
                placeholder="CAfe3c34616ef5d6038b0e6fd2ae6d144e (optional)"
                style={{ flex: 1 }}
              />
              <Button onClick={handleTriggerHIATest}>Trigger HIA</Button>
              {debugCallSid && (
                <Button appearance="subtle" onClick={() => setDebugCallSid('')}>Clear</Button>
              )}
            </div>
            {debugResult && (
              <Text size={200} style={{ display: 'block', marginTop: '8px' }}>
                {debugResult}
              </Text>
            )}
          </div>
        </>
      )}

      {callStatus === 'incoming' && activeCall && (
        <div className={styles.callCard}>
          <Text weight="semibold">Incoming call from {activeCall.from}</Text>
          <Text size={200} style={{ display: 'block', color: tokens.colorNeutralForeground3 }}>
            Accept/Reject via the Dynamics CIF toast.
          </Text>
        </div>
      )}

      {callStatus === 'in-progress' && activeCall && (
        <div className={styles.callCard}>
          <Text weight="semibold">On call with {activeCall.from}</Text>
          <Text size={200} style={{ display: 'block', color: tokens.colorNeutralForeground3 }}>
            CallSid: {activeCall.callSid}
            {activeCall.isSimulated && ' (simulated)'}
          </Text>
          <div className={styles.controls}>
            <Button onClick={handleToggleMute}>{isMuted ? 'Unmute' : 'Mute'}</Button>
            <Button appearance="primary" onClick={handleHangUp}>Hang up</Button>
          </div>
        </div>
      )}

      {switchDialog}
    </div>
  );
};

export default TwilioVoicePanel;
