import {
  Button,
  Spinner,
  Text,
  Textarea,
  makeStyles,
  shorthands,
  tokens,
} from '@fluentui/react-components';
import { Client, Conversation, Message } from '@twilio/conversations';

import { HIAConversationEventHelper } from '../common/utility/HIAConversationEventHelper';
import React from 'react';
import { Send24Regular } from '@fluentui/react-icons';

const useStyles = makeStyles({
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    ...shorthands.overflow('hidden'),
  },
  chatContainer: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    ...shorthands.padding('20px'),
    backgroundColor: tokens.colorNeutralBackground1,
  },
  infoSection: {
    backgroundColor: tokens.colorBrandBackground2,
    ...shorthands.padding('12px'),
    marginBottom: '12px',
    ...shorthands.borderRadius('4px'),
    ...shorthands.border('1px', 'solid', tokens.colorBrandStroke1),
  },
  messagesContainer: {
    flexGrow: 1,
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
    ...shorthands.borderRadius('4px'),
    ...shorthands.padding('15px'),
    marginBottom: '15px',
    backgroundColor: tokens.colorNeutralBackground3,
    overflowY: 'auto',
    scrollbarWidth: 'thin',
  },
  message: {
    ...shorthands.margin('10px', '0'),
    ...shorthands.padding('10px'),
    ...shorthands.borderRadius('8px'),
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke1),
  },
  messageMe: {
    backgroundColor: tokens.colorBrandBackground2,
    ...shorthands.borderColor(tokens.colorBrandStroke1),
    marginLeft: '40px',
  },
  messageOther: {
    backgroundColor: tokens.colorNeutralBackground2,
    marginRight: '40px',
  },
  messageAuthor: {
    fontWeight: 'bold',
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
    marginBottom: '5px',
  },
  messageBody: {
    fontSize: '14px',
    color: tokens.colorNeutralForeground1,
  },
  messageTime: {
    fontSize: '11px',
    color: tokens.colorNeutralForeground4,
    marginTop: '5px',
  },
  inputContainer: {
    display: 'flex',
    alignItems: 'flex-end',
    columnGap: '8px',
    ...shorthands.padding('12px'),
    backgroundColor: tokens.colorNeutralBackground1,
    ...shorthands.borderTop('1px', 'solid', tokens.colorNeutralStroke1),
  },
  inputField: {
    flexGrow: 1,
    minHeight: '40px',
    maxHeight: '120px',
  },
  sendButton: {
    minWidth: '40px',
    height: '40px',
  },
  loadingContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  errorText: {
    color: tokens.colorPaletteRedForeground1,
  },
});

interface TwilioMessage {
  author: string;
  body: string;
  dateCreated: Date;
}

const TwilioAgentPanel: React.FC = () => {
  const styles = useStyles();
  const [agentIdentity] = React.useState<string>('agent123');
  const [conversationId] = React.useState<string>('CH38d36ff613054a628be7f2f1faf60e21');
  const [intentFamilyId] = React.useState<string>('14f7c663-ed81-46d4-8cec-4cb1432bce57'); // Intent family for this conversation
  const [isLoading, setIsLoading] = React.useState<boolean>(true);
  const [error, setError] = React.useState<string | null>(null);
  const [messages, setMessages] = React.useState<TwilioMessage[]>([]);
  const [messageInput, setMessageInput] = React.useState<string>('');
  const [conversation, setConversation] = React.useState<Conversation | null>(null);
  const [currentIdentity, setCurrentIdentity] = React.useState<string>('');
  const messagesEndRef = React.useRef<HTMLDivElement>(null);

  const TOKEN_URL = 'https://chattryoutautogeneratedauthservice-6300.twil.io/token';

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  React.useEffect(() => {
    scrollToBottom();
  }, [messages]);

  React.useEffect(() => {
    const initializeChat = async () => {
      try {
        setIsLoading(true);
        setError(null);

        // Fetch token
        const response = await fetch(`${TOKEN_URL}?identity=${encodeURIComponent(agentIdentity)}`);

        if (!response.ok) {
          throw new Error(`Failed to get token: ${response.status} ${response.statusText}`);
        }

        const data = await response.json();

        // Create Twilio Conversations client
        const client = await Client.create(data.token);

        // Get conversation
        let conv: Conversation;
        try {
          conv = await client.getConversationBySid(conversationId);
        } catch (e) {
          throw new Error('Could not find conversation. Make sure the SID is correct and you are a participant.');
        }

        // Join conversation
        try {
          await conv.join();
        } catch (e) {
          // Already a participant
        }

        setCurrentIdentity(agentIdentity);
        setConversation(conv);

        // Load message history
        const messagesResponse = await conv.getMessages();
        const loadedMessages: TwilioMessage[] = messagesResponse.items.map((msg: Message) => ({
          author: msg.author || 'Unknown',
          body: msg.body || '',
          dateCreated: msg.dateCreated || new Date(),
        }));
        setMessages(loadedMessages);

        // 🔥 CIF Integration: Raise onConversationLoad event
        await HIAConversationEventHelper.raiseConversationLoad(
          conversationId,
          intentFamilyId
        );
        console.log('[HIA] onConversationLoad event raised', { conversationId, intentFamilyId });

        // Listen for new messages
        conv.on('messageAdded', async (message: Message) => {
          const newMsg: TwilioMessage = {
            author: message.author || 'Unknown',
            body: message.body || '',
            dateCreated: message.dateCreated || new Date(),
          };
          setMessages((prev) => [...prev, newMsg]);

          // 🔥 CIF Integration: Raise onCustomerMessageReceived event for customer messages
          // Only trigger for customer messages (not agent messages)
          if (message.author !== agentIdentity) {
            const messageId = message.sid || `msg_${Date.now()}`;
            const timestamp = message.dateCreated?.toISOString();

            await HIAConversationEventHelper.raiseCustomerMessageReceived(
              conversationId,
              messageId,
              timestamp
            );
            console.log('[HIA] onCustomerMessageReceived event raised', {
              conversationId,
              messageId,
              timestamp,
              author: message.author,
            });
          }
        });

        setIsLoading(false);
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Unknown error occurred');
        setIsLoading(false);
      }
    };

    initializeChat();
  }, [agentIdentity, conversationId, intentFamilyId, TOKEN_URL]);

  const handleSendMessage = async () => {
    const text = messageInput.trim();
    if (text && conversation) {
      try {
        await conversation.sendMessage(text);
        setMessageInput('');
      } catch (err) {
        console.error('Error sending message:', err);
      }
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  if (isLoading) {
    return (
      <div className={styles.loadingContainer}>
        <Spinner size="large" label="Connecting to Twilio chat..." />
      </div>
    );
  }

  if (error) {
    return (
      <div className={styles.loadingContainer}>
        <Text className={styles.errorText}>Error: {error}</Text>
      </div>
    );
  }

  return (
    <div className={styles.container}>
      <div className={styles.chatContainer}>
        <div className={styles.infoSection}>
          <Text weight="semibold">👤 Logged in as: </Text>
          <Text>{currentIdentity}</Text>
          <br />
          <Text weight="semibold">💬 Conversation: </Text>
          <Text>{conversationId}</Text>
        </div>

        <div className={styles.messagesContainer}>
          {messages.map((msg, index) => (
            <div
              key={index}
              className={`${styles.message} ${
                msg.author === currentIdentity ? styles.messageMe : styles.messageOther
              }`}
            >
              <div className={styles.messageAuthor}>{msg.author}</div>
              <div className={styles.messageBody}>{msg.body}</div>
              <div className={styles.messageTime}>
                {msg.dateCreated.toLocaleTimeString()}
              </div>
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>

        <div className={styles.inputContainer}>
          <Textarea
            className={styles.inputField}
            value={messageInput}
            onChange={(_, data) => setMessageInput(data.value)}
            onKeyDown={handleKeyPress}
            placeholder="Type a message... (Shift+Enter for new line)"
            resize="vertical"
            appearance="outline"
          />
          <Button
            appearance="primary"
            icon={<Send24Regular />}
            onClick={handleSendMessage}
            className={styles.sendButton}
            disabled={!messageInput.trim()}
          />
        </div>
      </div>
    </div>
  );
};

export default TwilioAgentPanel;
